question_data = [
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "easy", "category": "Science: Computers",
     "question": "In the programming language Java, which of these keywords would you put on a variable to make sure it doesn&#039;t get modified?",
     "correct_answer": "Final", "incorrect_answers": ["Static", "Private", "Public"]},
    {"type": "multiple", "difficulty": "easy", "category": "Science: Computers",
     "question": "In computing, what does LAN stand for?", "correct_answer": "Local Area Network",
     "incorrect_answers": ["Long Antenna Node", "Light Access Node", "Land Address Navigation"]},
    {"type": "multiple", "difficulty": "easy", "category": "Science: Computers",
     "question": "What does the computer software acronym JVM stand for?", "correct_answer": "Java Virtual Machine",
     "incorrect_answers": ["Java Vendor Machine", "Java Visual Machine", "Just Virtual Machine"]},
    {"type": "multiple", "difficulty": "easy", "category": "Science: Computers",
     "question": "On Twitter, what was the original character limit for a Tweet?", "correct_answer": "140",
     "incorrect_answers": ["120", "160", "100"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "Ada Lovelace is often considered the first computer programmer.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "multiple", "difficulty": "easy", "category": "Science: Computers",
                                       "question": "If you were to code software in this language you&#039;d only be able to type 0&#039;s and 1&#039;s.",
                                       "correct_answer": "Binary",
                                       "incorrect_answers": ["JavaScript", "C++", "Python"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "The Windows ME operating system was released in the year 2000.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "multiple", "difficulty": "easy", "category": "Science: Computers",
                                       "question": "The C programming language was created by this American computer scientist. ",
                                       "correct_answer": "Dennis Ritchie",
                                       "incorrect_answers": ["Tim Berners Lee", "al-Khw\u0101rizm\u012b",
                                                             "Willis Ware"]}]
